"""Pull the catalog from models.dev.

    python -m luca.client.catalog.refresh            # write the user cache
    python -m luca.client.catalog.refresh --vendor   # regenerate the shipped file

The cache is what a user refreshes; the vendored file is regenerated by a
maintainer and committed. Both go through the same fetch and mapping, so the two
files can never disagree about what a models.dev record means.

Neither write happens unless the fetch and the mapping both succeed, so a failed
refresh leaves whatever was already there.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ._data import VENDORED_PATH, cache_path, dump_records
from ._source import DEFAULT_TIMEOUT, CatalogSourceError, fetch_records


def refresh(*, vendor: bool = False, timeout: float = DEFAULT_TIMEOUT) -> tuple[Path, int, int]:
    """Fetch, map, write. Returns the path written, the record count, and the
    number of distinct providers. Raises `CatalogSourceError`."""
    records = fetch_records(timeout=timeout)
    if not records:
        raise CatalogSourceError("models.dev returned nothing luca can use — refusing to write an empty catalog")
    path = VENDORED_PATH if vendor else cache_path()
    dump_records(path, records)
    return path, len(records), len({record.provider for record in records})


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Refresh the luca model catalog from models.dev")
    parser.add_argument(
        "--vendor",
        action="store_true",
        help="Rewrite the file shipped in the package instead of the user cache.",
    )
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)
    args = parser.parse_args(argv)
    try:
        path, models, providers = refresh(vendor=args.vendor, timeout=args.timeout)
    except CatalogSourceError as exc:
        sys.stderr.write(f"luca: {exc}\n")
        return 1
    print(f"{models} models across {providers} providers -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
